name: Android CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.gitignore'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.gitignore'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Block certain users
      if: github.event_name == 'pull_request'
      run: |
        blocked_users=("suqi8")
        if [[ " ${blocked_users[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
          echo "Pull Request from user ${GITHUB_ACTOR} is blocked."
          exit 1
        fi
      shell: bash

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: | 
        ./gradlew assembleDebu
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
